### ISSUE TITLE
Material-UI: the createMuiTheme function was renamed to createTheme.

### ISSUE THREAD

**Issue by wel0z** [RoBYCoNTe/friendsofbabba-ra#1]
Material-UI: the createMuiTheme function was renamed to createTheme.
You should use `import { createTheme } from '@material-ui/core/styles'`

<img width="513" alt="Schermata 2022-04-12 alle 09 51 11" src="https://user-images.githubusercontent.com/6516617/162909398-5697a811-7f14-4ba2-ba2a-c6398f3d0582.png">

**Comment by RoBYCoNTe** [comment]
Will be resolved in next release, thanks for the suggestion.
